name: "CppLib"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - main
      - dev

env:
  MACOSX_DEPLOYMENT_TARGET: "10.15"

jobs:
  build:
    name: Cpp Lib
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-2019, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

#    - name: Setup interactive tmate session
#      uses: mxschmitt/action-tmate@v3

    - name: install xorg-dev on ubuntu
      run: ./ci_scripts/install_xorg_dev.sh

    - name: install conan and pybind11
      run: ./ci_scripts/install_conan_pybind11.sh

    - name: Build and install
      run: |
        mkdir build
        cd build
        cmake .. -DIMGUI_BUNDLE_WITH_IMMVISION=ON -DIMGUI_BUNDLE_BUILD_PYTHON=ON
        cmake --build .
