name: "CppLib_WithBindings"


on:
  workflow_dispatch:
  pull_request:
  push:

env:
  MACOSX_DEPLOYMENT_TARGET: "11.0"

jobs:
  build:
    name: CppLib_WithBindings
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

#    - name: Setup interactive tmate session
#      if: ${{ matrix.platform == 'ubuntu-latest' }}
#      uses: mxschmitt/action-tmate@v3

    - name: install xorg-dev on ubuntu
      run: ./ci_scripts/install_xorg_dev.sh

    - name: install pybind11
      run: |
        pip install pybind11

    - name: Build and install
      shell: bash
      run: |
        mkdir build
        cd build
        cmake .. -DIMGUI_BUNDLE_BUILD_PYTHON=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release -j 3
