name: "CppLib"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - main
      - dev


jobs:
  build:
    name: Cpp Lib
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
    env:
      if: ${{ matrix.platform == 'windows-latest' }}
      HELLO: World

    steps:
#      - name: set env win
#        if: ${{ matrix.platform == 'windows-2019' }}
#        run: Set-Variable -Name HELLO -Value World

      - name: echo env
        run: echo $HELLO
