name: "CppLib"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - main
      - dev

env:
  MACOSX_DEPLOYMENT_TARGET: "10.15"

jobs:
  build:
    name: Cpp Lib
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-2019, macos-latest, ubuntu-latest]
    env:
      if: ${{ matrix.platform == 'windows-2019' }}
      BLAH: ToiMeme

    steps:
#      - name: set env win
#        if: ${{ matrix.platform == 'windows-2019' }}
#        run: Set-Variable -Name BLAH -Value hello

      - name: echo env ALL
        run: echo $BLAH

      - name: echo env window
        if: ${{ matrix.platform == 'windows-2019' }}
        run: echo %BLAH%
